"""job_forms_table

Revision ID: 210195a9b526
Revises: 4c25eb88ca5e
Create Date: 2024-12-17 12:07:55.150472

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = '210195a9b526'
down_revision = '4c25eb88ca5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('job_forms',
    # sa.Column('job_id', sa.Integer(), nullable=False),
    # sa.Column('form_id', sa.Integer(), nullable=False),
    # sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ),
    # sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    # sa.PrimaryKeyConstraint('job_id', 'form_id')
    # )

    if environment == "production":
        op.execute(f"ALTER TABLE users SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('job_forms')
    pass
    # ### end Alembic commands ###
